"""Sync models

Revision ID: 7e5caa3d04a0
Revises: 0a8bb9716124
Create Date: 2024-12-05 20:48:25.481617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e5caa3d04a0'
down_revision: Union[str, None] = '0a8bb9716124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Hier keine drop_table- oder drop_index-Befehle enthalten.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Falls notwendig, spezifische Downgrade-Logik implementieren.
    pass
    # ### end Alembic commands ###
