version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    env_file: 
      - ../.env
    depends_on:
      - db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./unterschriften:/app/unterschriften
      - ./assets:/app/assets
      - ./uploads:/app/uploads 

  db:
    image: postgres:13
    env_file: 
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend

volumes:
  pg_data:
