"""Initial migration

Revision ID: fc665cde6a72
Revises: 
Create Date: 2024-12-07 10:21:30.574578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc665cde6a72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to keep existing tables ###
    # Keine Tabellen oder Indizes löschen, nur neue Änderungen hinzufügen oder bestehende Struktur übernehmen
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted ###
    # Entferne Änderungen, falls erforderlich
    pass
